### ISSUE TITLE
Stars should not be obtained for programs that do not pass the tests.

### ISSUE THREAD

**Issue by ppepos** [Morriar/Missions#53] opened 2016-08-25 18:05 UTC
Submission response:

``` json
{
"success": false,
"compilation_failed": false,
"compilation_messages": "",
"results" : 
[{"success": false, "message": ""Error: the result is not the expected one\n--- 57bcb6f66e955260ea537df6_PEPP03049109/sav.txt\t2016-08-25 14:02:42.462109433 -0400\n+++ 57bcb6f66e955260ea537df6_PEPP03049109/output.txt\t2016-08-25 14:02:42.470109600 -0400\n@@ -1 +1 @@\n-15\n+1\n""},{"success": false, "message": ""Error: the result is not the expected one\n--- 57bcb6f66e955260ea537df6_PEPP03049109/sav.txt\t2016-08-25 14:02:42.474109684 -0400\n+++ 57bcb6f66e955260ea537df6_PEPP03049109/output.txt\t2016-08-25 14:02:42.486109935 -0400\n@@ -1 +1 @@\n-10\n+1\n""},{"success": false, "message": ""Error: the result is not the expected one\n--- 57bcb6f66e955260ea537df6_PEPP03049109/sav.txt\t2016-08-25 14:02:42.490110018 -0400\n+++ 57bcb6f66e955260ea537df6_PEPP03049109/output.txt\t2016-08-25 14:02:42.494110102 -0400\n@@ -1 +1 @@\n-5\n+1\n""},{"success": false, "message": ""Error: the result is not the expected one\n--- 57bcb6f66e955260ea537df6_PEPP03049109/sav.txt\t2016-08-25 14:02:42.494110102 -0400\n+++ 57bcb6f66e955260ea537df6_PEPP03049109/output.txt\t2016-08-25 14:02:42.506110353 -0400\n@@ -1 +1 @@\n--40\n+1\n""}]
}
```

Log:

```
STAR unlocked Instruction CPU. 8 <= 24
STAR unlocked Taille du code machine. 3 <= 17
```

**Comment by privat** [comment] 2016-08-25 18:23
cannot reproduce. need more info

**Comment by privat** [comment] 2016-08-25 18:30
invalid

Do not report bug on non-merged code. Your issue is https://github.com/Morriar/Missions/pull/39/files#r76299515

**Closed as completed by privat** 2016-08-25 18:30 UTC
Labels: bug
